# Generated by Django 5.1.6 on 2025-06-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_attendee_unique_together_attendee_joined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
